name: Validate Sitemaps After Content Updates

on:
  push:
    branches: [main]
    paths:
      - "**/*.html"
      - ".github/workflows/sitemap-notify.yml"
  pull_request:
    paths:
      - "**/*.html"
      - ".github/workflows/sitemap-notify.yml"
  workflow_dispatch:

jobs:
  validate-sitemaps:
    uses: ./.github/workflows/submit-sitemap.yml
